### PR TITLE
fix warning from new react 18

### LINKED ISSUE #34: React 18 ReactDom.render
Please update template for react 18

### PR DESCRIPTION
**Pull request by Chensokheng**
Fixes #34

> Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot.

### CODE REVIEW

**Comment by Chensokheng** [comment]
@jeffposnick Could you review and merge this one?

**Review by jeffposnick — CHANGES_REQUESTED** [review]
Thanks for making this contribution!

Would you mind updating the `template.json` for the TypeScript flavor to match what was done in https://github.com/facebook/create-react-app/pull/12220/files#diff-ce7bf69b85ae95be024d754519acf3b1023258614bc9bf0e592b3fee9009fa69?

**Comment by Chensokheng** [comment]
@jeffposnick I just pushed a new update as you requested.

**Review by jeffposnick — APPROVED** [review]
Thank you! I'll push a new release to npm soon.

**Comment by jeffposnick** [comment]
This is now part of the v2.0.0 release on npm.

**Pull request merged**
